### ISSUE TITLE
Make dictionary *All() functions to 'talk' ie. list variables changed

### ISSUE THREAD

**Issue by epi-jhd** [Epiconcept-Paris/STRAP-epiuf#14]
Be useful to know what / if these functions have done when run on the whole dataset.

**Comment by epi-jhd** [comment]
See pull request for fix

**Comment by epi-jhd** [comment]
Subtask : Tidy dictionary function feebacks to be more logical and easy to retreive important information.

**Comment by epi-gde** [comment]
I someone want to give ideas , I would be happy to implemente ;)

**Comment by epi-jhd** [comment]
- *All functions do indeed 'talk' as their subsidiary functions talk. 
- They use cat rather than message to achieve this

Q: move subtask to new issue? this would be part of wider changes for creating a log. We are not there yet thus I propose we consider this issue as closed for now.
