### ISSUE TITLE
tab(...., data)  - can we add the default to be data=df ? 

### ISSUE THREAD

**Issue by epi-jhd** [Epiconcept-Paris/STRAP-epiuf#33]

**Comment by epi-gde** [comment]
What about a setData function , which could be used for any epiuf Function ? 
Using a df as default could be confusing because we have df everywhere ;)

**Comment by epi-jhd** [comment]
I see your point! I do not 'formally' use tab() in the script, but rather to check variables as I go along, and I always call whichever dataset I'm working 'df'.
