### ISSUE TITLE
Guide GitHub  

### ISSUE THREAD

**Issue by epi-gde** [Epiconcept-Paris/STRAP-epiuf#38]
the create_token function doesn't give enough access by default to be checked (notification, read package, team discussion at least are missing

**Comment by epi-gde** [comment]
Guide and setupgit.R script have been modified (in STRAP-Common-task)  to be tested during the next installation on a PC

**Comment by loremerdrignac** [comment]
Dear @epi-gde 
I run into this issue. Possibly we could close it now? :) We can check when we will be working back on the guidelines GitHub page.
Thanks!

**Comment by epi-gde** [comment]
Added to the GuideLine issue
