### ISSUE TITLE
New function needed: fillimage() to put graphs into excel sheets

### ISSUE THREAD

**Issue by epi-jhd** [Epiconcept-Paris/STRAP-epiuf#46]
Function can be based off insertImage() from openxlsx. 

fillimage <- function(image,line,col, wide=7, high=4 , unit = "in", spec.dpi=300, wb = NULL) {
  
  if (is.character(col)){
    col <- col2int(col)
  }
  listval <- list( ...)

    if (is.null(wb)) wb <- epixlsx_env$report
  
    insertImage( wb , onesheet, file = image, width = wide, height=high
                 , startCol = col, startRow = line, units=unit, dpi=spec.dpi)

}

**Comment by epi-jhd** [comment]
function made, needs review

**Comment by epi-jhd** [comment]
fillimage is already in the R package, and being used. Should I make a branch for it's review anyway??

`#' fillimage
#'
#' @param onesheet A sheet object from xlsx package
#' @param image The filename of a previously saved image 
#' @param line The line where to paste the image
#' @param col The col where to paste the image
#' @param wide Size of the image 
#' @param high Size of the image
#' @param unit For wide and high, default is "in" (Inch) 
#' @param spec.dpi 300 by default
#' @param wb  An optional wb if not already opened
#'  
#' @return Nothing
#'  
#' @export
#'
#' @examples 
#' \dontrun{ fillimage(onesheet = cells,image = graphname,line=2, col = 2, wb=template) }
#' 
fillimage <- function(onesheet,image,line,col, wide=7, high=4 , unit = "in", spec.dpi=300, wb = NULL) {
  
  if (is.character(col)){
    col <- openxlsx::col2int(col)
  }
  
  if (is.null(wb)) wb <- epixlsx_env$report
  
  openxlsx::insertImage( wb , onesheet, file = image, width = wide, height=high
                         , startCol = col, startRow = line, units=unit, dpi=spec.dpi)
  
  
}`

**Comment by epi-gde** [comment]
No need for a branch since the function is already there ;) 
But a review with asome manual test could be done (a vignette to show usage ?)

**Comment by epi-mml** [comment]
I've made a branch with a suggestion of improvment for the fillimage() function, it is the PR 121.
