### ISSUE TITLE
Amendment to setPath() : if folder does not exist - create!

### ISSUE THREAD

**Issue by epi-jhd** [Epiconcept-Paris/STRAP-epiuf#49]
It would be if setPath could create a folder if the named directory does not yet exist.

**Comment by loremerdrignac** [comment]
This feature was developped some time before version 0.4.0.0 :) with the argument 'makedir'. 
`setPath(pathname = "DATA", 
              path = "./data", 
              makedir = "Force")`

However, small improvements were added in the temporary branch "excel_output" and are pending a peer-review session (soon!!).

**Comment by loremerdrignac** [comment]
Test

**Comment by loremerdrignac** [comment]
Merged to main
