### ISSUE TITLE
function to edit elements of multiple dictionaries at once (variable names, dico names)

### ISSUE THREAD

**Issue by epi-jhd** [Epiconcept-Paris/STRAP-epiuf#51]
This might be a pie in the sky wish...But it would be very helpful!!!

Idea to be able to say 'find all dictionaries from this group which have generic_name = x and change it to y'
or 'find all dictionaries from this group which have dico code of x and change it to y in both dictioanary and dico sheet'.

**Comment by loremerdrignac** [comment]
Merged into another existing issue: Function to change a variable name everywhere #54

**Comment by loremerdrignac** [comment]
Merged into another existing issue: Function to change a variable name everywhere https://github.com/Epiconcept-Paris/STRAP-epiuf/issues/54
