### ISSUE TITLE
Function to change a variable name everywhere

### ISSUE THREAD

**Issue by epi-jhd** [Epiconcept-Paris/STRAP-epiuf#54]
Takes a list of scripts (and dictionaries?), find all instances of a variable name, and changes it.
Ditto for dico name and action group tag.
Perhaps this is a pipe dream! but I think it could be very useful thing to have in our pockets in the future.

Also, we merged with another issue: **Function to edit elements of multiple dictionaries at once (variable names, dico names) #51**
_"This might be a pie in the sky wish...But it would be very helpful!!!
Idea to be able to say 'find all dictionaries from this group which have generic_name = x and change it to y'
or 'find all dictionaries from this group which have dico code of x and change it to y in both dictioanary and dico sheet'."_

We also mentioned for dictionnaries to create a back-up of the files before applying the modifications, in case any mistake hapen. Nevertheless, we have GitHub of course as a backup :)

**Comment by loremerdrignac** [comment]
@epi-gde will demonstrate an existing a function so that we can decide if we investigate further or not
