### ISSUE TITLE
Function to specify format of specific cells when creating excel outputs using openXlsx/fillcells/saveXlsx suit of functions

### ISSUE THREAD

**Issue by epi-jhd** [Epiconcept-Paris/STRAP-epiuf#57]
Either sepcify which cells, OR by condition (eg <0.05)

 For example current strategy uses the openxlsx package:
# Make restriction group titles in bold
  s1 <- createStyle(textDecoration="bold") # set format
  rowsBold <- which(restab$Dropped=="")[-1] # select rows that which to make bold
  for (i in rowsBold+1){ # loop through rows, making them bold in 2 columns
  addStyle(results, "restrictions",style = s1, rows=i, cols=1)
  addStyle(results, "restrictions",style = s1, rows=i, cols=3)
  }

**Comment by epi-gde** [comment]
First version , we could also give a style and a condition ?

**Comment by loremerdrignac** [comment]
A second version of **fillCells()** has been developed in the branch "**excel_output**" and is pending a peer-review session with Gilles prior to be merged into the main branch.

Below a quick example of the current behavior:
```
# Creating an empty workbook
wb <- openxlsx::createWorkbook()

# Creating a new sheet
sheetname <- "First Sheet"
openxlsx::addWorksheet(wb, sheetName = sheetname)

# Writing a data frame in the workbook using a style to apply for a set of rows and columns
alertStyle <- createXlsxStyle(textDecoration = "Bold", fontColour = "red")
fillCells(wb = wb, 
          onesheet = sheetname, 
          line = 7, 
          col = 2, 
          iris, 
          style = alertStyle, 
          styleRowsIndex = which(iris$Sepal.Length<5),
          styleColsIndex = 1:4) 
```

**Comment by loremerdrignac** [comment]
Merge to main
